openapi: 3.0.0
info:
  title: People lister
  description: Implementation of this [API's](https://bpdts-test-app.herokuapp.com/) instructions
  license:
    name: MIT
    url: https://github.com/st3v3nhunt/people-lister/blob/master/LICENSE.md
  version: 0.1.0
servers:
- url: https://people-lister.azurewebsites.net/
  description: Production
paths:
  /people:
    get:
      summary: List people for locations and within specified distances
      description: The people end point returns users that are listed for the location or within the specified distance of the location
      operationId: People
      parameters:
        - in: query
          name: location
          required: true
          schema:
            type: string
          description: The location (a city) from where to search
        - in: query
          name: distance
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeopleResponse'
        400:
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/400Response'
        404:
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/404Response'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/500Response'
components:
  schemas:
    PeopleResponse:
      type: array
      items:
        type: object
      properties:
        id:
          type: integer
          description: The ID of the user
          example: 999
        first_name:
          type: string
          description: The first name of the user
          example: Toffee
        last_name:
          type: string
          description: The last name of the user
          example: Wrapper
        email:
          type: string
          description: The email address of the user
          example: delicious@sweet.shop
        ip_address:
          type: string
          description: The IPv4 address of the user
          example: "192.0.0.1"
        latitude:
          type: string
          description: The latitude of the user - it maybe a string or a number
          example: "9.8765"
        longitude:
          type: string
          description: The longitude of the user - it maybe a string or a number
          example: "50.1234"
    400Response:
      type: object
      properties:
        status:
          type: number
          description: The HTTP status code of the response
          example: 400
        detail:
          type: string
          description: The same as 'title' unless additional information is available to help diagnose the error
          example: "Bad Request"
        title:
          type: string
          description: The name of the HTTP status code
          example: "Bad Request"
    404Response:
      type: object
      properties:
        status:
          type: number
          description: The HTTP status code of the response
          example: 404
        detail:
          type: string
          description: The same as 'title' unless additional information is available to help diagnose the error
          example: "Not Found"
        title:
          type: string
          description: The name of the HTTP status code
          example: "Not Found"
    500Response:
      type: object
      properties:
        status:
          type: number
          description: The HTTP status code of the response
          example: 500
        detail:
          type: string
          description: The same as 'title' unless additional information is available to help diagnose the error
          example: "Internal Server Error"
        title:
          type: string
          description: The name of the HTTP status code
          example: "Internal Server Error"
